force-app/main/default/objects/AHA_ERL_Junction__c/AHA_ERL_Junction__c.object-meta.xml
<CustomObject>
    <label>AHA-ERL-Profile Junction</label>
    <nameField>
        <displayFormat>RSORJ-{000000}</displayFormat>
        <label>AHA-ERL Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AHA-ERL-Profile Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AHA_ERL_Junction__c/fields/ExternalIdentifier__c.field-meta.xml
<CustomField>
    <fullName>ExternalIdentifier__c</fullName>
    <externalId>true</externalId>
    <label>ExternalIdentifier</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AhaErlJunctionHelper.cls
/**
 * @description Trigger helper for AHA_ERL_Junction__c. Assigns a unique
 * ExternalIdentifier__c to newly inserted junction records that do not yet have one.
 */
public with sharing class AhaErlJunctionHelper {
    /**
     * @description Sets ExternalIdentifier__c on junctions in the given Id set that are
     * currently null, using the format 'AHAERLJ-{Id}'.
     * @param junctionids Ids of the newly inserted AHA_ERL_Junction__c records
     */
    public static void updateExternalIdentifier(Set<Id> junctionids) {
        List<AHA_ERL_Junction__c> junctionsToUpdate = [SELECT Id, ExternalIdentifier__c FROM AHA_ERL_Junction__c WHERE Id IN :junctionids AND ExternalIdentifier__c = null];
        if (!junctionsToUpdate.isEmpty()) {
            for (AHA_ERL_Junction__c junction : junctionsToUpdate) {
                junction.ExternalIdentifier__c = 'AHAERLJ-' + junction.Id;
            }
            update junctionsToUpdate;
        }
    }
}